---

#ansible_password: "{{ vault_ansible_password }}"
ansible_user: cool
ansible_ssh_private_key_file: '/home/cool/key/jenkins.priv'
ansible_python_interpreter: "/usr/bin/python3"
container_image: httpd
container_name: webapp
container_port_exposed: "8080:80"
public_folder: "/site-internet/."
src_folder_local_host: "/home/cool/index.html"
dest_folder_remote_host: "/tmp"
dest_folder_container: "/usr/local/apache2/htdocs/"
system_user: cool

